Callout control
WildGums/Orc.Controls pull request #354
Opened 2021-03-25 09:19 UTC by kote2ster

### Description of Change ###

We've added a new Callout Control with examples.

### Issues Resolved ### 

- fixes #345

### API Changes ###

 
Add new Callout Control.

### Platforms Affected ### 

- All
- WPF
- UWP
- iOS
- Android

### Behavioral Changes ###

None

### Testing Procedure ###

### PR Checklist ###

- [x] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

2021-03-25 09:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/WildGums/Orc.Controls?pullRequest=354) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/WildGums/Orc.Controls?pullRequest=354) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: kote2ster<br/>:x: 0matyesz0<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/WildGums/Orc.Controls?pullRequest=354) it.</sub>

2021-03-26 19:59 UTC, GeertvanHorrik requested changes

2021-03-26 19:59 UTC, GeertvanHorrik commented on src/Orc.Controls.Example/Views/MainWindow.xaml
> +            <TabItem Header="Callout">
Sort alphabetically

2021-03-26 19:59 UTC, GeertvanHorrik commented on src/Orc.Controls/Controls/Callout/Models/CalloutManager.cs
> +        public void UnRegister(CalloutViewModel callout)
Unregister (casing)

2021-03-26 19:59 UTC, GeertvanHorrik commented on src/Orc.Controls/Controls/Callout/Models/CalloutManager.cs
> +            if (calloutViewModel != null && callout != null)
please use "is not null". But even better, this method should throw when passing in null. So use:

Argument.IsNotNull(() => calloutViewModel);
Argument.IsNotNull(() => callout);

2021-03-26 19:59 UTC, GeertvanHorrik commented on src/Orc.Controls/Controls/Callout/Models/CalloutManager.cs
> +        public IList<CalloutViewModel> Callouts { get; set; } = new List<CalloutViewModel>();
Never return the original list to prevent issues.

2021-03-26 19:59 UTC, GeertvanHorrik commented on src/Orc.Controls/Controls/Callout/ViewModels/CalloutViewModel.cs
> +        public CalloutViewModel()
Inject Callout model

2021-03-26 19:59 UTC, GeertvanHorrik commented on src/Orc.Controls/Controls/Callout/Models/CalloutManager.cs
> +        public void Register(CalloutViewModel calloutViewModel, Callout callout)
Why would we need to VM besides the callout?

2021-03-26 19:59 UTC, GeertvanHorrik commented on src/Orc.Controls/Orc.Controls.csproj
> +    <Folder Include="Controls\Callout\ViewModels\" />
remove

2021-03-31 12:01 UTC, GeertvanHorrik requested changes
I miss the separation of the model (Callout) vs the view (CalloutView).

2021-03-31 12:01 UTC, GeertvanHorrik commented on src/Orc.Controls/Controls/Callout/Views/Callout.xaml.cs
> +        public object PlacementTarget
why object here, but UIElement in other places?

2021-03-31 12:27 UTC, GeertvanHorrik commented
The idea is that we have a model:

Callout (ICallout):
- Name
- Tag

View:

CalloutView:
- similar to what we have now

Whenever we register a callout (remember, a model, not a view), we can use it to dynamically show / hide it from within the manager. 

The view should register automatically in OnLoaded and unregister in OnUnloaded. This way we can work with the models (ICallout) everywhere and it should automatically work.

2021-03-31 12:44 UTC, GeertvanHorrik commented on src/Orc.Controls/Controls/Callout/Models/CalloutManager.cs
> +        public IList<Callout> Callouts { get; }
The issue here is that you are exposing internals (the list of callouts) to the external calls (they can change the *internal* collection).

Only register / unregister are allowed to change the registered callouts, not any other caller.

2021-03-31 12:46 UTC, GeertvanHorrik commented on src/Orc.Controls/Controls/Callout/Models/CalloutManager.cs
> +        public IList<Callout> Callouts { get; }
To give you an example, if I would do ICalloutManager.Callouts.Clear(), it would all be lost.

2021-03-31 14:31 UTC, 0matyesz0 commented
I'm not quite sure what should be the Tag's and Callout's (model) job.

Should we use a Tag property which holds a reference to an arbitrary object for the usercontrols in this case, every Callout Control should have a Tag property which is equal to a Callout model object ? And then somehow it would be easier to reference it in the manager after we registered the callout in the view ?

2021-03-31 20:16 UTC, GeertvanHorrik commented
Tag is indeed a "whatever you wish to assign to it".

I can see the CalloutView working great (you can put it somewhere and it will be used as popup). Then it should create a model / view model with a name (the name of the control could be a good one) and register it in the callout manager (InitializeAsync of the vm). Then it can also auto-unregister when the CalloutView gets unloaded (CloseAsync of the vm).

2021-04-06 14:57 UTC, 0matyesz0 commented
I was trying to keep in mind the things you mentioned and did the following changes:

CalloutView:
- Every added callout already has a viewmodel for this reason, in CalloutView we registered each callout with it's viewmodel that has various properties (For instance, the Callout's PlacementTarget's ControlName is one property.)
- Registering callouts works with subscribing an eventhandler to their (ViewModelChanged) event, and then in the handler we simply pass their viewmodel to the manager.
 
CalloutManager:
- At each callout register, it is the callout's viewmodel that the manager gets and adds to the callouts collection. This way the manager can simply change one callouts IsOpen property through its viewmodel to show it programitcally.
- The Callouts collection property's getter always returns just the copy of the original collection to avoid issues.

Callout:
- Every Callout has an additional Delay integer type Dp too, so now it's possible to set the time of popup delay in xaml code's attribute, then the manager handles all the callout appearings with the correct delay if it was given.

2021-04-24 11:54 UTC, GeertvanHorrik reviewed
I'll check out this code and make some improvements myself. Will give you and update this weekend.

2021-04-24 11:54 UTC, GeertvanHorrik commented on src/Orc.Controls.Example/Views/MainWindow.xaml.cs
> +using System;
I think all changes in this file are unnecessary.

2021-04-24 11:54 UTC, GeertvanHorrik commented on src/Orc.Controls/Controls/Callout/Models/CalloutManager.cs
> +        public IList<IViewModel> Callouts
It should be a list of ICallout objects. This way we can introduce new features *without breaking anything* in the future.

2021-04-24 11:54 UTC, GeertvanHorrik commented on src/Orc.Controls/Controls/Callout/Models/CalloutManager.cs
> +        private IList<IViewModel> _callouts;
fields before ctor

2021-04-24 11:54 UTC, GeertvanHorrik commented on src/Orc.Controls/Controls/Callout/Models/CalloutManager.cs
> +            set
I don't think we need to have a private setter.

2021-05-03 07:49 UTC, GeertvanHorrik commented
Made quite some changes to this. Will merge and improve on develop branch.

2021-05-03 07:50 UTC, merged